version: '3'

services:

  postgres:
    image: postgres:latest
    container_name: postgres_container
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: P3drobutt1e$$
      POSTGRES_DB: bit_videoanalisis
    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:      
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} -t 1"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 10s

  web:
    build: ./web
    ports:
      - "80:5000"
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql+psycopg2://postgres:P3drobutt1e$$@postgres:5432/bit_videoanalisis
    depends_on:
      postgres:
        condition: service_healthy    
    links: 
        - postgres


  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: buttiepedro2000@gmail.com
      PGADMIN_DEFAULT_PASSWORD: P3drobutt1e$$
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin-data:
